fixtures:
  repositories:
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '2.2.1'
    haproxy:
      repo: 'git://github.com/puppetlabs/puppetlabs-haproxy.git'
      ref: '1.5.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.11.0'
  symlinks:
    haproxywrapper: "#{source_dir}"
